# Generated by Django 3.0.2 on 2020-08-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='etimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='stimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='start_time',
        ),
        migrations.AddField(
            model_name='user_data',
            name='ending_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endtime', to='data_app.etimings'),
        ),
        migrations.AddField(
            model_name='user_data',
            name='starting_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starttime', to='data_app.stimings'),
        ),
    ]
