# Generated by Django 3.0.2 on 2020-08-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_auto_20200807_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='starting_time',
        ),
        migrations.DeleteModel(
            name='etimings',
        ),
        migrations.DeleteModel(
            name='stimings',
        ),
    ]
