# Generated by Django 3.0.2 on 2020-08-06 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_auto_20200807_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 1, 58, 57, 650454)),
        ),
        migrations.AddField(
            model_name='user_data',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 1, 58, 57, 650454)),
        ),
    ]
