# Generated by Django 3.0.2 on 2020-08-06 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_auto_20200807_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timings',
            name='stimings',
        ),
        migrations.AlterField(
            model_name='timings',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 2, 16, 43, 314139)),
        ),
    ]
