# Generated by Django 3.0.2 on 2020-08-06 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0006_auto_20200807_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='stimings',
            field=models.ManyToManyField(to='data_app.timings'),
        ),
        migrations.AlterField(
            model_name='timings',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 2, 17, 20, 43809)),
        ),
    ]
