# Generated by Django 3.0.2 on 2020-08-06 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0009_auto_20200807_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='timings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 8, 7, 2, 21, 16, 461129))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2020, 8, 7, 2, 21, 16, 461129))),
            ],
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='start_time',
        ),
    ]
