# Generated by Django 3.0.2 on 2020-08-06 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0011_auto_20200807_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='date_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 8, 7, 2, 43, 32, 851194))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2020, 8, 7, 2, 43, 32, 851194))),
            ],
        ),
        migrations.DeleteModel(
            name='timings',
        ),
    ]
