# Generated by Django 3.0.2 on 2020-08-06 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0012_auto_20200807_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_time',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='data_app.user_data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='date_time',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 2, 56, 43, 461549)),
        ),
        migrations.AlterField(
            model_name='date_time',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 2, 56, 43, 461549)),
        ),
    ]
