# Generated by Django 3.0.2 on 2020-08-06 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0014_auto_20200807_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_time',
            old_name='album',
            new_name='timings',
        ),
        migrations.AlterField(
            model_name='date_time',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 3, 13, 7, 397541)),
        ),
        migrations.AlterField(
            model_name='date_time',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 3, 13, 7, 397541)),
        ),
    ]
