# Generated by Django 3.0.2 on 2020-08-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0018_user_data_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='timezone',
        ),
    ]
