# Generated by Django 3.0.2 on 2020-08-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0021_auto_20200808_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='timezone',
        ),
    ]
